### ISSUE TITLE
[QUESTION] Pre-fill of data opens the dropdown

### ISSUE THREAD

**Issue by dittmarconsulting** [xuopled/react-google-places-suggest#12]
Hi there,

Love the little library and it works like a charm.

I have a question regarding pre-filling the input with data. 

Let's say the `react-google-places-suggest` is part of a form that needs to be pre-filled with data from a table and the location property is a string such as `New York, NY, United States`.  

I can set the values via **state** like this:
```
componentWillMount() {
  this.setState({ search: this.props.selectedData.location })
}
```

It sets the text correctly but it opens the dropdown. Is there a way to select the correct entry and close the dropdown?

Thanks for your support
Thomas

**Comment by xuopled** [comment]
Hi, thank you for your interest in this lib.

It seems you can't do that with the last version.

I did not need this feature for now because, I use `react-google-places-suggest` with [react-google-map](https://github.com/xuopled/react-google-map) so when I prefill data on my form, my map is refreshed.
![capture d ecran 2017-08-17 a 10 10 19](https://user-images.githubusercontent.com/2683300/29402196-664ada7e-8334-11e7-952f-579f1127eb5b.png)

PR are welcome :)

**Comment by dittmarconsulting** [comment]
Thanks for the quick reply @xuopled 

I'll investigate any options and let you know.

I don't know whether I have time for a PR though.

**Comment by xuopled** [comment]
Hi @dittmarconsulting, you need to checkout the new v3. You could do what you want to do.

You can separate search and value. If you fill the value and set input to "", it could be ok
```js
<ReactGooglePlacesSuggest
                autocompletionRequest={{input: search}}
                googleMaps={googleMaps}
                onSelectSuggest={this.handleSelectSuggest.bind(this)}
              >
                <input
                  type="text"
                  value={value}
                  placeholder="Search a location"
                  onChange={this.handleInputChange.bind(this)}
                />
              </ReactGooglePlacesSuggest>
```

**Comment by xuopled** [comment]
I close this issue. Feel free to reopen it if you still get the problem
