### ISSUE TITLE
Remove styled-components

### ISSUE THREAD

**Issue by albinekb** [xuopled/react-google-places-suggest#25]
Every time I install a library that uses this library I get prompted to give money to styled-components.
![image](https://user-images.githubusercontent.com/5027156/37464264-1a769182-2858-11e8-949e-df500c09cde0.png)

I don't want to use styled-components, would you be open to a PR that removed usage of this lib?

**Comment by xuopled** [comment]
Hi @albinekb, what do you propose ? I'm open to remove it but it will be a major breaking change.
It could be great to do like [downshift](https://github.com/paypal/downshift): Use a render prop to export primitives and let the user the choice for styling. But if we do that, we need to provide a default theme.

I'm open, feel free to open a PR

**Comment by xuopled** [comment]
I was not aware of that point. I agree, it's a bit too much from them

Le 15 mars 2018 19:30, "Albin Ekblom" <notifications@github.com> a écrit :

Sorry I was a bit fed up today, I just think it's a bit too much by
styled-components to be asking about money every-time I install a lib that
uses it underneath. I'll check the codebase out and see what I can do,
otherwise I'll close this. Thanks 👍

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xuopled/react-google-places-suggest/issues/25#issuecomment-373478594>,
or mute the thread

**Comment by xuopled** [comment]
So so you want to help me about this or do you want to close it?

**Comment by albinekb** [comment]
It's fine.. thanks 👍 Let's close this, I haven't had any problems with it, just annoying on first install 😄
