### ISSUE TITLE
Display "powered by Google" logo?

### ISSUE THREAD

**Issue by manovotny** [xuopled/react-google-places-suggest#41]
According to Google's place autocomplete documentation:

> **Note**: When you display predictions from Place Autocomplete, you must include the '[powered by Google](https://developers.google.com/places/web-service/policies)' logo. This logo is included in the results list by default, as shown in the above example.
> 
> \- [Source](https://developers.google.com/maps/documentation/javascript/places-autocomplete#fig1)

![Screen Shot 2019-03-25 at 10 19 27 AM](https://user-images.githubusercontent.com/446260/54931715-8a869b00-4ee7-11e9-9525-7dc8e361bbb1.png)

We can add that ourselves via the component's `customContainerRender` prop, but it seems like something the component should handle natively / automatically. ***Do you agree?*** If so, our team would be happy to contribute a PR to add it to the module.

**Comment by xuopled** [comment]
You are right. I would be grateful if you contribute with a PR to help me about this :)

Could you add a prop to disable it in case of someone would like to customize the render with `customContainerRender`?

Thank you very much

**Comment by BradyKDavis** [comment]
We are working on a fix to this and adding a prop to selectively show the "Powered By Google" logo with the default view. However, because the `customContainerRender` is a function provided by the consumer, the consumer would have to add the "Powered By Google" logo themselves since we have no access into the container function itself.

To alleviate this issue, we would provide a component that the consumer can use in their layout, since we cannot append it within their `customContainerRender` function. Thoughts on this approach?

**Comment by xuopled** [comment]
It could be a good idea. An other way could be to use `customContainerRender` to customize only list result. The google logo will be at the bottom and still manageable by the prop you added

**Comment by xuopled** [comment]
Fixed with `v3.7.0`
